---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: awx-work-volume
spec:
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 4Gi
  storageClassName: awx-work-volume
  hostPath:
    path: /data/work
