---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: galaxy

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: redhat-operators-pull-secret
    literals:
      - operator=eda

resources:
  - github.com/ansible/galaxy-operator/config/default?ref=2024.5.8

images:
  - name: quay.io/ansible/galaxy-operator
    newTag: 2024.5.8
